version: '2'
services:
  foreignexchange-app:
    image: foreignexchange
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://foreignexchange-postgresql:5432/foreignExchange
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8090:8090
  foreignexchange-postgresql:
    extends:
      file: postgresql.yml
      service: foreignexchange-postgresql
